triggermesh/tmctl

.goreleaser.yaml, README.md, cmd/create/broker.go, cmd/create/source.go, cmd/create/target.go, cmd/create/transformation.go, cmd/create/trigger.go, cmd/delete/delete.go, cmd/describe/describe.go, cmd/sendevent/sendevent.go, cmd/start/start.go, cmd/stop/stop.go, cmd/watch/watch.go, pkg/log/log.go, pkg/triggermesh/components/components.go, pkg/triggermesh/components/service/service.go, pkg/triggermesh/crd/crd.go
1. Inplace `log` package replacement for additional context output
2. Triggers update/cleanup logic fix for transformation/targets creation. Closes #126 
3. `--from-image` services restart check fixed
=> Log output update, trigger add/update fixes

README.md, cmd/watch/watch.go, pkg/docker/client.go, pkg/triggermesh/components/source/source.go, pkg/triggermesh/components/target/target.go, pkg/wiretap/wiretap.go
1. User feedback: `tmctl watch` prints broker subscription updates,
2. Resource name check condition fixed, resolves #116.
=> Watch broker config, fix CRD resources listing

cmd/create/broker.go, cmd/create/cmd.go, cmd/create/completion.go, cmd/create/source.go, cmd/create/target.go, cmd/create/transformation.go, cmd/create/trigger.go, cmd/delete/delete.go, cmd/describe/describe.go, cmd/dump/dump.go, cmd/sendevent/sendevent.go, cmd/start/start.go, cmd/stop/stop.go, cmd/watch/watch.go
The `dump` command checks if the manifest contains the components with external resources and prints the warning message to help avoid race conditions.
Additionally, internal CLI structures unexported to improve linting situation.
=> Dump warning message

cmd/cmd.go, pkg/triggermesh/components/broker/broker.go, pkg/triggermesh/constants.go, pkg/triggermesh/crd/crd.go
1. Config default values and structure moved to `pkg/triggermesh` package,
2. Broker default values exposed in CLI's config file,
3. Components' default version is set to either latest available at the moment of the CLI's first start or to the hardcoded default. Overridable through the config file or global `--version` parameter.
=> Broker parameters in CLI config

cmd/create/broker.go, cmd/create/cmd.go, cmd/create/completion.go, cmd/create/source.go, cmd/create/target.go, cmd/create/transformation.go, cmd/create/trigger.go, cmd/delete/delete.go, cmd/describe/describe.go, cmd/dump/dump.go, cmd/sendevent/sendevent.go, cmd/start/start.go, cmd/stop/stop.go, cmd/watch/watch.go, pkg/kubernetes/object.go, pkg/triggermesh/components/components.go, pkg/triggermesh/components/source/source.go, pkg/triggermesh/components/target/target.go, pkg/triggermesh/components/transformation/transformation.go, pkg/triggermesh/constants.go, pkg/triggermesh/interfaces.go
1. `Reconcilable` interface supplemented with `GetExternalResources` method that returns the list of external resources created by reconcilable component,
2. `tmctl dump` checks if the manifest contains running reconcilable components and prints the warning message about events race conditions to stderr.
3. Unrelated. Local `cmd/` structures were un-exported to help with code scoping and linting in future code quality work.
=> `tmctl dump` warns about external resources

cmd/cmd.go, cmd/create/completion.go, cmd/create/source.go, cmd/create/target.go, cmd/create/transformation.go, cmd/create/trigger.go, cmd/watch/watch.go, docs/tmctl_create.md, docs/tmctl_create_source.md, docs/tmctl_create_target.md, docs/tmctl_create_transformation.md, docs/tmctl_create_trigger.md, docs/tmctl_watch.md, pkg/output/output.go, pkg/triggermesh/components/broker/broker.go, pkg/triggermesh/constants.go
This PR contains two fixes that should be in the 1.0.0 version:
1. On the Windows OS, CLI's default config will contain an additional parameter that switches Broker to config polling mode. 
2. `--event-types` flag across all commands replaced with `--eventTypes` for consistency.
=> Broker config for Windows. Event type flag consistent across commands

cmd/create/cmd.go
Arguments with 2 leading `-` are considered to be flag names; before this fix, any number (>=2) of `-` made the argument accepted as a flag name.
Resolves #189
=> Better flag name identification

cmd/cmd.go, cmd/describe/describe.go, cmd/logs/logs.go, cmd/sendevent/sendevent.go, cmd/start/start.go, docs/tmctl.md, docs/tmctl_logs.md, pkg/docker/client.go, pkg/triggermesh/adapter/adapter.go, pkg/triggermesh/components/broker/broker.go, pkg/triggermesh/components/service/service.go, pkg/triggermesh/components/source/source.go, pkg/triggermesh/components/target/target.go, pkg/triggermesh/components/transformation/transformation.go, pkg/triggermesh/interfaces.go, pkg/wiretap/wiretap.go
1. `alert`, `fatal` and `panic` added to the trigger-words for container startup validation procedure, read logs operation simplified. Resolves #198 
2. `tmctl logs [name] [-f]` command added to provide easier access to adapter container logs. Closes #201
=> Logs interaction improvements

cmd/create/target.go, cmd/create/transformation.go, cmd/create/trigger.go, cmd/describe/describe.go, docs/tmctl_create_trigger.md, go.mod, go.sum, pkg/triggermesh/adapter/reconciler/external/gcp/billingsource.go, pkg/triggermesh/components/broker/trigger.go
1. Values passed with `--eventTypes` flag now can contain `*` symbol as a **prefix** or **suffix** to set trigger's filtering condition to "prefix" or "suffix" accordingly, related to #215,
2. `tmctl create trigger` supports `--filter` argument which, if passed, will be encoded directly into filter structure and passed to trigger specification, e.g.: 
```
tmctl create trigger --target sockeye --filter '{"Not":{"Exact":{"source":"foo"}}}'
```
3. `tmctl describe` updated to work with new possible triggers output
=> Events filtering improvements

.gitignore, cmd/cmd.go, cmd/config/cmd.go, pkg/config/config.go, pkg/config/overrides.go, pkg/docker/client.go, pkg/wiretap/wiretap.go
- `container.Connect` method that checked the container's TCP port on the local Docker host is replaced with the container's status inspection using the Docker client. With this update, CLI should not require the Docker engine to run on the local host,
- Container initialization timeout configurable through the CLI configuration file,
- Container startup logs validation improvement - check unstructured log data for Go's panic dump.
Related to triggermesh/triggermesh#1287
=> Skip TCP connection on localhost

cmd/create/trigger.go
This PR provides a fix for an issue described in #221.
Updated behavior for `tmctl create trigger` command with multiple eventTypes filter and single trigger name - `--name foo --eventTypes a,b,c` will result in triggers `foo-1`, `foo-2`, and `foo-3` with `a`, `b`, and `c` type filters to be created. Details of the proposed fix are [here](https://github.com/triggermesh/tmctl/issues/221#issuecomment-1410378957).
=> Trigger name with multiple eventTypes fix

cmd/cmd.go, cmd/create/cmd.go, cmd/delete/delete.go, cmd/describe/describe.go, cmd/dump/dump.go, cmd/logs/logs.go, cmd/sendevent/sendevent.go, cmd/start/start.go, cmd/stop/stop.go
Fix for autocompletion - the previous update removed preload of the default manifest required for completion functions to list existing objects
=> Preload manifest for completion

go.mod, go.sum, pkg/triggermesh/adapter/ce/sources.go, pkg/triggermesh/adapter/ce/targets.go, pkg/triggermesh/adapter/env/flow.go, pkg/triggermesh/adapter/env/sources.go, pkg/triggermesh/adapter/env/targets.go
Sync with the latest TriggerMesh.
Removed:
- AlibabaOSSTarget
- HasuraTarget
- TektonTarget
- DataWeaveTransformation
- ConfluentTarget
Added:
- SolaceSource
- SolaceTarget
- MongoDBTarget
=> Sync TriggerMesh components

pkg/triggermesh/components/source/source.go, pkg/triggermesh/components/target/target.go, pkg/triggermesh/crd/crd.go
There are edge cases when retrieving (custom version) component's event attributes from the imported method is failing, i.e. object won't pass conversion to `unstructured.Unstructured` if the new CRD has an incompatible change. For these cases, sources and now targets will try to parse CRD's event attribute annotations to get this data if it is available.
=> Fallback to CRD event annotations if reconciler's method is failing

cmd/create/transformation.go, docs/tmctl.md, docs/tmctl_brokers.md, docs/tmctl_config.md, docs/tmctl_config_get.md, docs/tmctl_config_set.md, docs/tmctl_create.md, docs/tmctl_create_broker.md, docs/tmctl_create_source.md, docs/tmctl_create_target.md, docs/tmctl_create_transformation.md, docs/tmctl_create_trigger.md, docs/tmctl_delete.md, docs/tmctl_describe.md, docs/tmctl_dump.md, docs/tmctl_import.md, docs/tmctl_logs.md, docs/tmctl_send-event.md, docs/tmctl_start.md, docs/tmctl_stop.md, docs/tmctl_version.md, docs/tmctl_watch.md, go.mod, go.sum, pkg/triggermesh/adapter/ce/targets.go, pkg/triggermesh/components/transformation/transformation.go
This PR contains transformation-related updates:
- triggermesh/triggermesh dependency updated to v1.24.4 version,
- updated HTTPTarget behavior (strict event type, schema, etc.) employed in the CLI's internals,
- CLI automatically sets CE context transformation to match produced and expected events.
=> CE transformation improvements

cmd/delete/broker.go, cmd/delete/cmd.go, cmd/delete/source.go, cmd/delete/target.go, cmd/delete/transformation.go, cmd/delete/trigger.go, docs/tmctl.md, docs/tmctl_delete.md, docs/tmctl_delete_broker.md, docs/tmctl_delete_source.md, docs/tmctl_delete_target.md, docs/tmctl_delete_transformation.md, docs/tmctl_delete_trigger.md, pkg/completion/completion.go, test/e2e/run_e2e_test.sh
`tmctl delete` command, now being consistent with the `create` format, expects the component's kind and name args to execute the deletion, e.g.:
```sh
tmctl delete source foo
tmctl delete transformation bar
tmctl delete broker baz
```
etc.
=> `tmctl delete` command format update

cmd/dump/dump.go, pkg/kubernetes/object.go, pkg/triggermesh/components/broker/broker.go, pkg/triggermesh/components/service/service.go, pkg/triggermesh/components/source/source.go, pkg/triggermesh/components/target/target.go, pkg/triggermesh/components/transformation/transformation.go, pkg/triggermesh/interfaces.go
Experimental, low-effort feature that enables TriggerMesh integration deployment on any Kubernetes clusters with no prerequisites - `tmctl dump -p kubernetes-generic` produces vanilla Kubernetes Deployment objects. Can be `| kubectl apply -f -`'d on "empty" Minikube. One detail to keep in mind - if integration components require external services reconciliation, this process will take place in the CLI during initial creation, just like in any other cases.
=> `tmctl dump -p kubernetes-generic` 

cmd/create/trigger.go
This PR fails the `create trigger` command when args other than flags are detected.
Fixes: #229
=> fail create trigger command when extra args are detected

cmd/stop/stop.go, cmd/watch/watch.go, docs/tmctl.md, docs/tmctl_brokers.md, docs/tmctl_config.md, docs/tmctl_config_get.md, docs/tmctl_config_set.md, docs/tmctl_create.md, docs/tmctl_create_source.md, docs/tmctl_create_target.md, docs/tmctl_create_transformation.md, docs/tmctl_create_trigger.md, docs/tmctl_delete.md, docs/tmctl_delete_broker.md, docs/tmctl_delete_source.md, docs/tmctl_delete_target.md, docs/tmctl_delete_transformation.md, docs/tmctl_delete_trigger.md, docs/tmctl_describe.md, docs/tmctl_dump.md, docs/tmctl_import.md, docs/tmctl_logs.md, docs/tmctl_send-event.md, docs/tmctl_start.md, docs/tmctl_stop.md, docs/tmctl_version.md, docs/tmctl_watch.md
This PR adds changes to clean up the wiretap container specific to a broker when `tmctl stop` is used to stop a broker container.
Fixes: #205
=> cleanup the wiretap container specific to the broker in case of tmctl stop

cmd/sendevent/sendevent.go, docs/tmctl_send-event.md
This PR adds  `-f` flag to the `send-event` command for specifying the file containing events.
Fixes: #220
=> add file flag to send-event to specify file containing multiple events

cmd/watch/watch.go, docs/tmctl_watch.md, pkg/wiretap/wiretap.go
[CreateTrigger](https://github.com/triggermesh/tmctl/blob/main/pkg/wiretap/wiretap.go#L85) function has an unnecessary parameter. 
Maybe forgot to remove it after the function structure was changed.
=> remove the unnecessary argument in the CreateTrigger func in wiretap
